name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Se connecter à GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Builder et pusher l'image
        uses: docker/build-push-action@v5
        with:
          context: repo_depart
          target: api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/churnguard:${{ github.ref_name }}

      - name: Créer la release avec notes automatiques
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true